name: simple_autocomplete_search
description: Simple autocomplete field with suggestions. You can customize the onPressed function and filtering function.
version: 1.0.4
homepage: "https://spotforest.com"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
